# Cloud Build configuration
# Build + push to Artifact Registry, then deploy to Cloud Run.
# Intended to be run by a TAG trigger (e.g. v1.2.3)

substitutions:
  _REGION: us-central1
  _REPOSITORY: cloud-run-source-deploy   # Artifact Registry repository name
  _IMAGE: colosseum        # Image name within the repo
  _SERVICE: colosseum      # Cloud Run service name

steps:
  # Guardrails: enforce "tag-trigger only" and required substitutions.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    script: |
      #!/usr/bin/env bash
      set -euo pipefail

      if [[ -z "${TAG_NAME:-}" ]]; then
        echo "TAG_NAME is not set. Configure Cloud Build trigger to run on tag pushes."
        exit 1
      fi

      : "${_RUN_SA:?Missing _RUN_SA substitution (Cloud Run runtime service account email)}"
      : "${_INSTANCE_CONNECTION_NAME:?Missing _INSTANCE_CONNECTION_NAME (PROJECT:REGION:INSTANCE)}"
      : "${_DB_USER:?Missing _DB_USER}"
      : "${_DB_NAME:?Missing _DB_NAME}"
      : "${_ALLOWED_EMAIL_DOMAINS:?Missing _ALLOWED_EMAIL_DOMAINS}"
      : "${_APP_URL:?Missing _APP_URL}"
  # Build the Docker image once and tag it three ways.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$TAG_NAME
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
      - .

  # Push all tags.
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$TAG_NAME"]

  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"]

  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest"]

  # Deploy Cloud Run to the exact release tag, with runtime wiring.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$TAG_NAME
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated

      # Runtime identity + Cloud SQL attachment
      - --service-account
      - ${_RUN_SA}
      - --add-cloudsql-instances
      - ${_INSTANCE_CONNECTION_NAME}

      # Non-secret runtime config (use ^@^ delimiter so commas inside
      # ALLOWED_EMAIL_DOMAINS are not misinterpreted as pair separators)
      - --set-env-vars
      - ^@^NODE_ENV=production@DB_USER=${_DB_USER}@DB_NAME=${_DB_NAME}@CLOUD_SQL_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}@ALLOWED_EMAIL_DOMAINS=${_ALLOWED_EMAIL_DOMAINS}@APP_URL=${_APP_URL}

      # Secret Manager bindings (names are constants; versions can be :latest)
      - --set-secrets
      - DB_PASSWORD=colosseum-db-password:latest,SESSION_SECRET=colosseum-session-secret:latest,GOOGLE_CLIENT_ID=colosseum-google-client-id:latest,GOOGLE_CLIENT_SECRET=colosseum-google-client-secret:latest

      # Resource/scaling knobs (keep these identical across deploy paths)
      - --memory
      - 512Mi
      - --cpu
      - "1"
      - --min-instances
      - "0"
      - --max-instances
      - "10"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$TAG_NAME
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
